version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
