name: 'Multiplatform Build'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  MACOS_CEF_BUILD_VERSION: '4183'
  LINUX_CEF_BUILD_VERSION: '4280'
  CEF_VERSION: '75.1.16+g16a67c4+chromium-75.0.3770.100'
  TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENT_ID }}
  TWITCH_HASH: ${{ secrets.TWITCH_HASH }}
  RESTREAM_CLIENTID: ${{ secrets.RESTREAM_CLIENTID }}
  RESTREAM_HASH: ${{ secrets.RESTREAM_HASH }}
  YOUTUBE_CLIENTID: ${{ secrets.YOUTUBE_CLIENTID }}
  YOUTUBE_CLIENTID_HASH: ${{ secrets.YOUTUBE_CLIENTID_HASH }}
  YOUTUBE_SECRET: ${{ secrets.YOUTUBE_SECRET }}
  YOUTUBE_SECRET_HASH: ${{ secrets.YOUTUBE_SECRET_HASH }}

jobs:
  win32:
    name: 'Windows 32-bit'
    runs-on: 'windows-latest'
    env:
      GH_TOKEN: ${{secrets.gh_token}}
      WINDOWS_DEPS_VERSION: '2019'
      WINDOWS_DEPS_CACHE_VERSION: '2'
    steps:
      - name: 'Add msbuild to PATH'
        uses: microsoft/setup-msbuild@v1.0.2
      - name: 'Checkout'
        uses: actions/checkout@v2.3.3
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: '10.20.1'
      - run: npm i
      - run: npm run build